# Generated by Django 5.2.8 on 2025-11-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('divan', 'Divanlar'), ('krovat', 'Krovatlar'), ('stol', 'Stollar'), ('shkaf', 'Shkaflar'), ('yotoqxona', 'Yotoqxona Mebellari')], max_length=100)),
                ('image', models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
        ),
    ]
